name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  style:
    runs-on: ubuntu-latest
    name: Check Style
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25'
          elixir-version: '1.14.0'
      - run: mix deps.unlock --check-unused
      - run: mix deps.get --only test
      - run: mix format --check-formatted
      - run: mix credo --strict

  test:
    runs-on: ubuntu-latest
    name: Tests on latest version
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25'
          elixir-version: '1.14.0'
      - run: rm mix.lock
      - run: mix deps.get --only test
      - run: mix compile --force --warnings-as-errors
      - run: mix test
      - run: mix dialyzer
